export function SiteFooter() {
  return (
    <footer className="border-t border-rule">
      <div className="mx-auto max-w-6xl px-4 py-8 text-sm text-ink-faint sm:px-6">
        <p>
          GenAI ReleaseGate — statistical release gating for production LLM agents. Every
          number on this site is read from{" "}
          <code className="font-mono text-xs">results/reports/*.json</code>, generated by the
          real evaluation pipeline. This site makes no live model or guardrail calls.
        </p>
        <p className="mt-2">
          <a
            href="https://github.com/irishz12/GenAI-Evaluation-Guardrails"
            className="underline underline-offset-2 hover:text-ink"
          >
            Source on GitHub
          </a>
        </p>
      </div>
    </footer>
  );
}
